apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "presto.hive" . }}
  labels:
    app: {{ template "presto.name" . }}
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  hive.properties: |
    connector.name=hive-hadoop2
    hive.metastore.uri={{ .Values.hive.metastore.uri }}
    hive.allow-drop-table=true
    hive.s3.endpoint={{ .Values.hive.s3.endpoint }}
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled={{ .Values.hive.s3.ssl.enabled }}
    hive.s3.max-connections={{ index .Values "hive" "s3" "max-connections" }}
    hive.s3.aws-access-key={{ index .Values "hive" "s3" "aws-access-key" }}
    hive.s3.aws-secret-key={{ index .Values "hive" "s3" "aws-secret-key" }}

---